# Generated by Django 2.2.5 on 2019-09-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(to='main_app.Player'),
        ),
    ]
